spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/auth/realms/one
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:resolution
admin.user-id: 328167d1-2da3-5f7a-86d7-96b4376af2c0

logging:
  level:
    org:
      springframework: debug
